"""Build 384px member sheets (WebP) + assets/chibi/members.js from the original chibi exports.

Usage:
    python tools/make-chibi.py [path-to-source-folder]

Default source is assets/source/nmoi (original exports, kept in the repo).

Each member folder must contain <id>-sheet.png and <id>-manifest.json.
Requires Pillow (pip install pillow).
"""
import hashlib
import json
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LONG = "\\\\?\\"   # \\?\ prefix: allow paths over 260 chars on Windows
if os.name == "nt" and not ROOT.startswith(LONG):
    ROOT = LONG + ROOT
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "assets", "source", "nmoi")
OUT = os.path.join(ROOT, "assets", "chibi")
CELL = 384   # native size of the exports: on 3x phones the serving chibi is ~470 device px tall, 256 looked soft
MEMBERS = ["nara", "natalie", "serin", "tiya", "yoon"]
NAMES = {"nara": "나라", "natalie": "나탈리", "serin": "세린", "tiya": "티야", "yoon": "유온"}

os.makedirs(OUT, exist_ok=True)
members = []
for mid in MEMBERS:
    m = json.load(open(os.path.join(SRC, mid, mid + "-manifest.json"), encoding="utf-8"))
    sheet = Image.open(os.path.join(SRC, mid, mid + "-sheet.png")).convert("RGBA")
    src_cell = m["animation"]["cellWidth"]
    rows = m["animation"]["rows"]
    nrows = max(r["row"] for r in rows.values()) + 1
    ncols = max(r["frames"] for r in rows.values())
    out = Image.new("RGBA", (ncols * CELL, nrows * CELL), (0, 0, 0, 0))
    bbox = None
    for name, r in rows.items():
        for f in range(r["frames"]):
            cell = sheet.crop((f * src_cell, r["row"] * src_cell,
                               (f + 1) * src_cell, (r["row"] + 1) * src_cell))
            small = cell.resize((CELL, CELL), Image.LANCZOS)
            out.paste(small, (f * CELL, r["row"] * CELL))
            if name == "idle":  # body bounds, used to centre and scale the sprite
                b = small.getchannel("A").point(lambda a: 255 if a > 40 else 0).getbbox()
                if b:
                    bbox = b if bbox is None else (min(bbox[0], b[0]), min(bbox[1], b[1]),
                                                   max(bbox[2], b[2]), max(bbox[3], b[3]))
    out.save(os.path.join(OUT, mid + ".webp"), "WEBP", quality=90, method=6)
    members.append({
        "id": mid,
        "name": NAMES.get(mid, mid.capitalize()),
        # ?v=<content hash>: a rebuilt sheet gets a new URL, so no phone keeps an old one
        "sheet": "assets/chibi/" + mid + ".webp?v=" + hashlib.md5(
            open(os.path.join(OUT, mid + ".webp"), "rb").read()).hexdigest()[:8],
        "cell": CELL,
        "bounds": {"x": bbox[0], "y": bbox[1], "w": bbox[2] - bbox[0], "h": bbox[3] - bbox[1]},
        "anims": {k: {"row": v["row"], "frames": v["frames"], "fps": v["fps"], "loop": v["loop"]}
                  for k, v in rows.items()},
    })
    print(mid, out.size, os.path.getsize(os.path.join(OUT, mid + ".webp")), "bytes")

js = ("/* Generated by tools/make-chibi.py - 384px cells. Regenerate when art changes. */\n"
      "(function (NS) {\n  'use strict';\n  NS.members = "
      + json.dumps(members, indent=2, ensure_ascii=False).replace("\n", "\n  ")
      + ";\n})(window.CAVIAR = window.CAVIAR || {});\n")
open(os.path.join(OUT, "members.js"), "w", encoding="utf-8").write(js)
